# See more config options https://github.com/foundry-rs/foundry/tree/master/config
[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# Sets the concrete solc version to use
# This overrides the `auto_detect_solc` value
# solc_version = '0.8.13'

remappings = [
  "@std=lib/forge-std/src/",
  "@openzeppelin=lib/openzeppelin-contracts/contracts/",
]
